name: alphamplyer_utils
description: A bunch of methods / extension that I use on my projects
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
